resilience4j:
    circuitbreaker:
        instances:
            userService:
               registerHealthIndicator: true
               slidingWindowSize: 10
               minimumNumberOfCalls: 5
               failureRateThreshold: 50
               waitDurationInOpenState: 10s
               permittedNumberOfCallsInHalfOpenState: 3
    retry:
      instances:
        orderService:
              maxRetryAttempts: 3
              waitDuration: 2s
server:
    port: 8091
spring:
    application:
             name: user-service
eureka:
    client:
       service-url:
            defaultZone: http://localhost:8762/eureka/
management:
       endpoints:
            web:
              exposure:
                  include: "*"
