eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
server:
  port: 9005
spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
