eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8083

spring:
  application:
    name: inventory-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
